image: python:3.7-alpine

pages:
  stage: deploy
  script:
  - pip install -U sphinx
  - pip install sphinx-autopackagesummary
  - pip install sphinx-autodoc-typehints
  - PYTHONPATH=. sphinx-build doc/src/ doc/html/
  artifacts:
    paths:
    - public
  only:
  - master
